version: '3.8'
services:
postgres:
image: postgres:13
environment:
POSTGRES_DB: productmanagement
POSTGRES_USER: productapp
POSTGRES_PASSWORD: securepassword
ports:
- "5432:5432"
volumes:
- postgres_data:/var/lib/postgresql/data
redis:
image: redis:6.2
ports:
- "6379:6379"
rabbitmq:
image: rabbitmq:3-management
ports:
- "5672:5672"
- "15672:15672"
api:
build:
context: .
dockerfile: Dockerfile.api
depends_on:
- postgres
- redis
- rabbitmq
environment:
- DB_HOST=postgres
- REDIS_HOST=redis
- RABBITMQ_HOST=rabbitmq
image-processor:
build:
context: .
dockerfile: Dockerfile.image-processor
depends_on:
- postgres
- rabbitmq
environment:
- DB_HOST=postgres
- RABBITMQ_HOST=rabbitmq
volumes:
postgres_data: